/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schooladmisssion;
import java.sql.*;
/**
 *
 * @author Administrator
 */
public class feePaid extends javax.swing.JFrame {

    /**
     * Creates new form feePaid
     */
    public feePaid() {
        objcn = new DBConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbladdno = new javax.swing.JLabel();
        lblinstallmentno = new javax.swing.JLabel();
        lblamountpaid = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        lblreciptno = new javax.swing.JLabel();
        lblbalanceamount = new javax.swing.JLabel();
        txtaddno = new javax.swing.JTextField();
        txtinstalmentno = new javax.swing.JTextField();
        txtamountpaid = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        txtreciptnumber = new javax.swing.JTextField();
        txtbalanceamount = new javax.swing.JTextField();
        btnaddfeeinfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbladdno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdno.setText("Addmission Number");

        lblinstallmentno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblinstallmentno.setText("Instalment Number");

        lblamountpaid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblamountpaid.setText("Amount Paid");

        lbldate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldate.setText("Date");

        lblreciptno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblreciptno.setText("Recipt Number");

        lblbalanceamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblbalanceamount.setText("Balance Amount");

        txtaddno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddnoActionPerformed(evt);
            }
        });

        txtbalanceamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceamountActionPerformed(evt);
            }
        });

        btnaddfeeinfo.setText("Add");
        btnaddfeeinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddfeeinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbladdno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblinstallmentno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblamountpaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblreciptno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblbalanceamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtaddno, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtinstalmentno)
                            .addComponent(txtamountpaid)
                            .addComponent(txtdate)
                            .addComponent(txtreciptnumber)
                            .addComponent(txtbalanceamount)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnaddfeeinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladdno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblinstallmentno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtinstalmentno, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtamountpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblamountpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbldate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblreciptno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreciptnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbalanceamount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbalanceamount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnaddfeeinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaddnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddnoActionPerformed

    private void txtbalanceamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalanceamountActionPerformed

    private void btnaddfeeinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddfeeinfoActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("Add"))
        {
            try
            {
                String datePaid = txtdate.getText();
                java.util.Date objDate = new java.util.Date(datePaid);
                java.sql.Date objSqlDate = new java.sql.Date(objDate.getTime());
                st = objcn.cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery("select addno,instalmentnumber,amountpaid,paiddate,reciptnumber,balance from feepaid");
                if(rs!=null)
                {
                    rs.moveToInsertRow();
                    rs.updateString("addno",txtaddno.getText());
                    rs.updateString("instalmentnumber",txtinstalmentno.getText());
                    rs.updateString("amountpaid",txtamountpaid.getText());
                    rs.updateDate("paiddate", objSqlDate);
                    rs.updateString("reciptnumber",txtreciptnumber.getText());
                    rs.updateString("balance",txtbalanceamount.getText());
                    rs.insertRow();
                }
            }
            catch(SQLException sqle)
            {
                System.out.println("Sql exception : "  +sqle);
               //to know the error line number
                sqle.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnaddfeeinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feePaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feePaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feePaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feePaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feePaid().setVisible(true);
            }
        });
    }

    //dbconnection object
     DBConnection objcn;
     //Statement st
    Statement st;
    //ResultSet
    ResultSet rs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddfeeinfo;
    private javax.swing.JLabel lbladdno;
    private javax.swing.JLabel lblamountpaid;
    private javax.swing.JLabel lblbalanceamount;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblinstallmentno;
    private javax.swing.JLabel lblreciptno;
    private javax.swing.JTextField txtaddno;
    private javax.swing.JTextField txtamountpaid;
    private javax.swing.JTextField txtbalanceamount;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtinstalmentno;
    private javax.swing.JTextField txtreciptnumber;
    // End of variables declaration//GEN-END:variables
}
