/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schooladmisssion;

import java.sql.*;


/**
 *
 * @author Administrator
 */
public class school extends javax.swing.JFrame {

    /**
     * Creates new form school
     */
    public school() {
        objcn = new DBConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblname = new javax.swing.JLabel();
        lblestablishmentyear = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtestablishmentyear = new javax.swing.JTextField();
        lblinstitutionname = new javax.swing.JLabel();
        txtinstitutioname = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblwebsite = new javax.swing.JLabel();
        txtwebsite = new javax.swing.JTextField();
        lbladdress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taaddress = new javax.swing.JTextArea();
        btnsaveinfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name");
        getContentPane().add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 68, 100, 30));

        lblestablishmentyear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblestablishmentyear.setText("Establishment Year");
        getContentPane().add(lblestablishmentyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 110, -1, 30));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 68, 100, 30));

        txtestablishmentyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestablishmentyearActionPerformed(evt);
            }
        });
        getContentPane().add(txtestablishmentyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 110, 100, 30));

        lblinstitutionname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblinstitutionname.setText("Institution Name");
        getContentPane().add(lblinstitutionname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 152, 100, 30));
        getContentPane().add(txtinstitutioname, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 152, 100, 30));

        lblphoneno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblphoneno.setText("Phone Number");
        getContentPane().add(lblphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 194, 100, 30));
        getContentPane().add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 194, 100, 30));

        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblemail.setText("E-mail");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 236, 100, 30));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 236, 100, 30));

        lblwebsite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblwebsite.setText("Website");
        getContentPane().add(lblwebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 278, 100, 30));

        txtwebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtwebsiteActionPerformed(evt);
            }
        });
        getContentPane().add(txtwebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 278, 100, 30));

        lbladdress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdress.setText("Address");
        getContentPane().add(lbladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 320, 100, 30));

        taaddress.setColumns(20);
        taaddress.setRows(5);
        jScrollPane1.setViewportView(taaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 320, -1, -1));

        btnsaveinfo.setText("Save Info");
        btnsaveinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveinfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnsaveinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 424, 120, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtestablishmentyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestablishmentyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestablishmentyearActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtwebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtwebsiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtwebsiteActionPerformed

    private void btnsaveinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveinfoActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("Save Info"))
        {
            try
            {
                st=objcn.cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                rs=st.executeQuery("select name,establishmentyear,institutionname,phoneno,email,website,address from school");
                if(rs!=null)
                {
                    rs.moveToInsertRow();
                    rs.updateString("name", txtname.getText());
                    rs.updateString("establishmentyear", txtestablishmentyear.getText());
                    rs.updateString("institutionname", txtinstitutioname.getText());
                    rs.updateString("phoneno",txtphoneno.getText());
                    rs.updateString("email", txtemail.getText());
                    rs.updateString("website", txtwebsite.getText());
                    rs.updateString("address",taaddress.getText());
                    rs.insertRow();
                }
            }
            catch(SQLException sqle)
            {
                
            }
        }
    }//GEN-LAST:event_btnsaveinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(school.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(school.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(school.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(school.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new school().setVisible(true);
            }
        });
    }
    //dbconnection object
     DBConnection objcn;
     //Statement st
    Statement st;
    //ResultSet
    ResultSet rs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsaveinfo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblestablishmentyear;
    private javax.swing.JLabel lblinstitutionname;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblwebsite;
    private javax.swing.JTextArea taaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtestablishmentyear;
    private javax.swing.JTextField txtinstitutioname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtwebsite;
    // End of variables declaration//GEN-END:variables
}
