package schooladmisssion;

import java.sql.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class studentProfile extends javax.swing.JFrame {

    /**
     * Creates new form studentProfile
     */
    public studentProfile() {
        objcn = new DBConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsatsno = new javax.swing.JLabel();
        txtsatsno = new javax.swing.JTextField();
        lbladdno = new javax.swing.JLabel();
        txtaddno = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lbldob = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        lblsaadhar = new javax.swing.JLabel();
        txtsaadhar = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        lblfqualification = new javax.swing.JLabel();
        txtfqualification = new javax.swing.JTextField();
        lblfoccupation = new javax.swing.JLabel();
        txtfoccupation = new javax.swing.JTextField();
        lblfaadhar = new javax.swing.JLabel();
        txtfaadhar = new javax.swing.JTextField();
        lblmname = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        lblmqualification = new javax.swing.JLabel();
        txtmqualification = new javax.swing.JTextField();
        lblmoccupation = new javax.swing.JLabel();
        txtmoccupation = new javax.swing.JTextField();
        lblmaadhar = new javax.swing.JLabel();
        txtmaadhar = new javax.swing.JTextField();
        lblgname = new javax.swing.JLabel();
        txtgname = new javax.swing.JTextField();
        lblgaddress = new javax.swing.JLabel();
        lblannualincome = new javax.swing.JLabel();
        txtannualincome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagaddress = new javax.swing.JTextArea();
        lbladdress = new javax.swing.JLabel();
        lbladdresscorrespondance = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taaddress = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taaddresscorrspondance = new javax.swing.JTextArea();
        lblsphono = new javax.swing.JLabel();
        txtsphono = new javax.swing.JTextField();
        lblpphono = new javax.swing.JLabel();
        txtpphono = new javax.swing.JTextField();
        lblreligion = new javax.swing.JLabel();
        txtreligion = new javax.swing.JTextField();
        lblcaste = new javax.swing.JLabel();
        txtcaste = new javax.swing.JTextField();
        lblmothertoung = new javax.swing.JLabel();
        txtmothertoung = new javax.swing.JTextField();
        lbldisablilities = new javax.swing.JLabel();
        txtdisablities = new javax.swing.JTextField();
        btnupdatestudentprofile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblsatsno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsatsno.setText("SAT's Number");

        txtsatsno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsatsnoActionPerformed(evt);
            }
        });

        lbladdno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdno.setText("Addmission Number");

        txtaddno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddnoActionPerformed(evt);
            }
        });

        lblname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblname.setText("Name");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        lbldob.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldob.setText("Date Of Birth");

        lblgender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblgender.setText("Gender");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        lblsaadhar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsaadhar.setText("Student Aadhar Number");

        lblfname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblfname.setText("Father's Name");

        lblfqualification.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblfqualification.setText("Father's Qualification");

        lblfoccupation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblfoccupation.setText("Father's Occupation");

        txtfoccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfoccupationActionPerformed(evt);
            }
        });

        lblfaadhar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblfaadhar.setText("Father's Aadhar Namber");

        lblmname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmname.setText("Mother's Name");

        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });

        lblmqualification.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmqualification.setText("Mother's Qualification");

        txtmqualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmqualificationActionPerformed(evt);
            }
        });

        lblmoccupation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmoccupation.setText("Mother's Occupation");

        lblmaadhar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmaadhar.setText("Mother's Aadhar Number");

        lblgname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblgname.setText("Guardian Name");

        lblgaddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblgaddress.setText("Guardian Address");

        lblannualincome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblannualincome.setText("Annual Income");

        tagaddress.setColumns(20);
        tagaddress.setRows(5);
        jScrollPane1.setViewportView(tagaddress);

        lbladdress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdress.setText("Address");

        lbladdresscorrespondance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdresscorrespondance.setText("Address For Correspondance");

        taaddress.setColumns(20);
        taaddress.setRows(5);
        jScrollPane2.setViewportView(taaddress);

        taaddresscorrspondance.setColumns(20);
        taaddresscorrspondance.setRows(5);
        jScrollPane3.setViewportView(taaddresscorrspondance);

        lblsphono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsphono.setText("Student Phone Number");

        lblpphono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpphono.setText("Parent Phone Number");

        txtpphono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpphonoActionPerformed(evt);
            }
        });

        lblreligion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblreligion.setText("Religion");

        lblcaste.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcaste.setText("Caste");

        lblmothertoung.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmothertoung.setText("Mother Toung");

        lbldisablilities.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldisablilities.setText("Disablilities");

        btnupdatestudentprofile.setText("Update Student Profile");
        btnupdatestudentprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatestudentprofileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldisablilities, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmothertoung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcaste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblreligion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblpphono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsphono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbladdresscorrespondance, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(lbladdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblannualincome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblgaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblgname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmaadhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmoccupation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmqualification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblmname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblfaadhar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblfoccupation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblfqualification, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblfname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsaadhar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblgender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbladdno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsatsno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtsatsno, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtfoccupation)
                                .addComponent(txtgender, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtaddno)
                                .addComponent(txtdob, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsaadhar)
                                .addComponent(txtfname)
                                .addComponent(txtfqualification)
                                .addComponent(txtfaadhar)
                                .addComponent(txtmname, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(txtmqualification)
                                .addComponent(txtmoccupation)
                                .addComponent(txtmaadhar)
                                .addComponent(txtgname))
                            .addComponent(txtannualincome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdisablities, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(txtmothertoung, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcaste, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtreligion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpphono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsphono, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(83, 83, 83))))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnupdatestudentprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsatsno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsatsno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbladdno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmqualification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmaadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblgaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtannualincome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblannualincome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladdresscorrespondance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsphono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsphono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpphono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpphono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcaste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcaste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmothertoung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmothertoung, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldisablilities, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdisablities, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnupdatestudentprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsatsnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsatsnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsatsnoActionPerformed

    private void txtaddnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddnoActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtfoccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfoccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfoccupationActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtpphonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpphonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpphonoActionPerformed

    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void txtmqualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmqualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmqualificationActionPerformed

    private void btnupdatestudentprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatestudentprofileActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("Add Subject Info"))
        {
            try
            {
                st = objcn.cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery("select satsnum,addno,name,dob,gender,stuaadhar,fname,fqualification,foccupation,faadhar,mname,mqualification,moccupation,maadhar,gname,gaddress,annualincome,address,addresscorrespondance,stuphono,parentphno,religion,caste,mothertoung,disabilities from studentprofie");
                if(rs!=null)
                {
                    rs.moveToInsertRow();
                    rs.updateString("satsnum",txtsatsno.getText());
                    rs.updateString("addno",txtaddno.getText());
                    rs.updateString("name",txtname.getText());
                    rs.updateString("dob",txtdob.getText());
                    rs.updateString("gender",txtgender.getText());
                    rs.updateString("stuaadhar",txtsaadhar.getText());
                    rs.updateString("fname",txtfname.getText());
                    rs.updateString("fqualification",txtfqualification.getText());
                    rs.updateString("foccupation",txtfoccupation.getText());
                    rs.updateString("faadhar",txtfaadhar.getText());
                    rs.updateString("mname",txtname.getText());
                    rs.updateString("mqualification",txtmqualification.getText());
                    rs.updateString("moccupation",txtmoccupation.getText());
                    rs.updateString("maadhar",txtmaadhar.getText());
                    rs.updateString("gname",txtgname.getText());
                    rs.updateString("gaddress",tagaddress.getText());
                    rs.updateString("annualincome",txtannualincome.getText());
                    rs.updateString("address",taaddress.getText());
                    rs.updateString("addresscorrespondance",taaddresscorrspondance.getText());
                    rs.updateString("stuphono",txtsphono.getText());
                    rs.updateString("parentphno",txtpphono.getText());
                    rs.updateString("religion",txtreligion.getText());
                    rs.updateString("caste",txtcaste.getText());
                    rs.updateString("mothertoung",txtmothertoung.getText());
                    rs.updateString("disabilities",txtdisablities.getText());
                    rs.insertRow();
                }
            }
            catch(SQLException sqle)
            {

            }
        }
    }//GEN-LAST:event_btnupdatestudentprofileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentProfile().setVisible(true);
            }
        });
    }

    //dbconnection object
     DBConnection objcn;
     //Statement st
    Statement st;
    //ResultSet
    ResultSet rs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdatestudentprofile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbladdno;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lbladdresscorrespondance;
    private javax.swing.JLabel lblannualincome;
    private javax.swing.JLabel lblcaste;
    private javax.swing.JLabel lbldisablilities;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblfaadhar;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblfoccupation;
    private javax.swing.JLabel lblfqualification;
    private javax.swing.JLabel lblgaddress;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblgname;
    private javax.swing.JLabel lblmaadhar;
    private javax.swing.JLabel lblmname;
    private javax.swing.JLabel lblmoccupation;
    private javax.swing.JLabel lblmothertoung;
    private javax.swing.JLabel lblmqualification;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblpphono;
    private javax.swing.JLabel lblreligion;
    private javax.swing.JLabel lblsaadhar;
    private javax.swing.JLabel lblsatsno;
    private javax.swing.JLabel lblsphono;
    private javax.swing.JTextArea taaddress;
    private javax.swing.JTextArea taaddresscorrspondance;
    private javax.swing.JTextArea tagaddress;
    private javax.swing.JTextField txtaddno;
    private javax.swing.JTextField txtannualincome;
    private javax.swing.JTextField txtcaste;
    private javax.swing.JTextField txtdisablities;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtfaadhar;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfoccupation;
    private javax.swing.JTextField txtfqualification;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtgname;
    private javax.swing.JTextField txtmaadhar;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmoccupation;
    private javax.swing.JTextField txtmothertoung;
    private javax.swing.JTextField txtmqualification;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpphono;
    private javax.swing.JTextField txtreligion;
    private javax.swing.JTextField txtsaadhar;
    public javax.swing.JTextField txtsatsno;
    private javax.swing.JTextField txtsphono;
    // End of variables declaration//GEN-END:variables
}
