/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schooladmisssion;
import java.sql.*;

/**
 *
 * @author Administrator
 */
public class studentAcademic extends javax.swing.JFrame {

    /**
     * Creates new form studentAcademic
     */
    public studentAcademic() {
        objcn = new DBConnection();
        System.out.println(objcn);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        lblclassname = new javax.swing.JLabel();
        lbladdno = new javax.swing.JLabel();
        lblsection = new javax.swing.JLabel();
        lbllanguage1 = new javax.swing.JLabel();
        lbllanguage2 = new javax.swing.JLabel();
        lbldateofaddmission = new javax.swing.JLabel();
        lblmediumnow = new javax.swing.JLabel();
        lblprevious = new javax.swing.JLabel();
        lblpreviousschooladdress = new javax.swing.JLabel();
        txtclassname = new javax.swing.JTextField();
        txtaddno = new javax.swing.JTextField();
        txtsection = new javax.swing.JTextField();
        txtlanguage1 = new javax.swing.JTextField();
        txtlanguage2 = new javax.swing.JTextField();
        txtdateofaddmission = new javax.swing.JTextField();
        txtmediumnow = new javax.swing.JTextField();
        txtmediumprevious = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tapreviousschooladdress = new javax.swing.JTextArea();
        lblisstudentfrombegining = new javax.swing.JLabel();
        btnupdateacademicinfo = new javax.swing.JButton();
        lblpreviousschool = new javax.swing.JLabel();
        txtpreviousschool = new javax.swing.JTextField();
        txtisstudentfrombeginning = new javax.swing.JTextField();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblclassname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblclassname.setText("Class Name");

        lbladdno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbladdno.setText("Addmission Number");

        lblsection.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsection.setText("Section");

        lbllanguage1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbllanguage1.setText("Language 1");

        lbllanguage2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbllanguage2.setText("Language 2");

        lbldateofaddmission.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbldateofaddmission.setText("Date of Addmission");

        lblmediumnow.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmediumnow.setText("Medium Now");

        lblprevious.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblprevious.setText("Medium Previous");

        lblpreviousschooladdress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpreviousschooladdress.setText("Previous School Address");

        txtclassname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclassnameActionPerformed(evt);
            }
        });

        txtaddno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddnoActionPerformed(evt);
            }
        });

        txtlanguage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlanguage1ActionPerformed(evt);
            }
        });

        txtlanguage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlanguage2ActionPerformed(evt);
            }
        });

        txtmediumnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmediumnowActionPerformed(evt);
            }
        });

        tapreviousschooladdress.setColumns(20);
        tapreviousschooladdress.setRows(5);
        jScrollPane1.setViewportView(tapreviousschooladdress);

        lblisstudentfrombegining.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblisstudentfrombegining.setText("Is Student From Beginning");

        btnupdateacademicinfo.setText("Update Student Academic Info");
        btnupdateacademicinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateacademicinfoActionPerformed(evt);
            }
        });

        lblpreviousschool.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblpreviousschool.setText("Previous School");

        txtpreviousschool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreviousschoolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblclassname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbladdno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblsection, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbllanguage1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbllanguage2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldateofaddmission, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmediumnow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprevious, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblpreviousschool, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblpreviousschooladdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblisstudentfrombegining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtaddno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtclassname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsection, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlanguage2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlanguage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdateofaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmediumnow, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmediumprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpreviousschool, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtisstudentfrombeginning, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnupdateacademicinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblclassname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtclassname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbladdno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblsection, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtsection, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtlanguage1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbllanguage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllanguage2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlanguage2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateofaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdateofaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmediumnow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmediumnow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblprevious, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtmediumprevious))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblpreviousschool, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtpreviousschool))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpreviousschooladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblisstudentfrombegining, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtisstudentfrombeginning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnupdateacademicinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclassnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclassnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclassnameActionPerformed

    private void txtaddnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddnoActionPerformed

    private void txtlanguage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlanguage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlanguage2ActionPerformed

    private void txtmediumnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmediumnowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmediumnowActionPerformed

    private void txtpreviousschoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreviousschoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreviousschoolActionPerformed

    private void txtlanguage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlanguage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlanguage1ActionPerformed

    private void btnupdateacademicinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateacademicinfoActionPerformed
        // TODO add your handling code here:
        if(evt.getActionCommand().equals("Update Student Academic Info"))
        {
            try
            {
                String dateOfAddmission = txtdateofaddmission.getText();
                java.util.Date objDateOfAddmission = new java.util.Date(dateOfAddmission);
                java.sql.Date objSqlDateOfAddmission = new java.sql.Date(objDateOfAddmission.getTime());
                st = objcn.cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery("select classname,addno,section,language1,language2,dateofaddmission,mediumnow,mediumprevious,previousschool,previousschooladdress,issutudentfrombeginning from studentacademic");
                //System.out.println("RS: "+rs);
                if(rs!=null)
                {
                    rs.moveToInsertRow();
                    rs.updateString("classname",txtclassname.getText());
                    rs.updateString("addno",txtaddno.getText());
                    rs.updateString("section",txtsection.getText());
                    rs.updateString("language1",txtlanguage1.getText());
                    rs.updateString("language2",txtlanguage2.getText());
                    rs.updateDate("dateofaddmission",objSqlDateOfAddmission);
                    rs.updateString("mediumnow",txtmediumnow.getText());
                    rs.updateString("mediumprevious",txtmediumprevious.getText());
                    rs.updateString("previousschool",txtpreviousschool.getText());
                    rs.updateString("previousschooladdress",tapreviousschooladdress.getText());
                    rs.updateString("issutudentfrombeginning",txtisstudentfrombeginning.getText());
                    rs.insertRow();
                }
            }
            catch(SQLException sqle)
            {
                   System.out.println("there is an exception");
                   System.out.println("Sqle"+sqle);
                   sqle.printStackTrace();
            }
            displayInfo objdis=new displayInfo();
            objdis.setVisible(true);
        }
    }//GEN-LAST:event_btnupdateacademicinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentAcademic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentAcademic().setVisible(true);
            }
        });
    }
    

    //dbconnection object
     DBConnection objcn;
     //Statement st
    Statement st;
    //ResultSet
    ResultSet rs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdateacademicinfo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladdno;
    private javax.swing.JLabel lblclassname;
    private javax.swing.JLabel lbldateofaddmission;
    private javax.swing.JLabel lblisstudentfrombegining;
    private javax.swing.JLabel lbllanguage1;
    private javax.swing.JLabel lbllanguage2;
    private javax.swing.JLabel lblmediumnow;
    private javax.swing.JLabel lblprevious;
    private javax.swing.JLabel lblpreviousschool;
    private javax.swing.JLabel lblpreviousschooladdress;
    private javax.swing.JLabel lblsection;
    private javax.swing.JTextArea tapreviousschooladdress;
    private javax.swing.JTextField txtaddno;
    private javax.swing.JTextField txtclassname;
    private javax.swing.JTextField txtdateofaddmission;
    private javax.swing.JTextField txtisstudentfrombeginning;
    private javax.swing.JTextField txtlanguage1;
    private javax.swing.JTextField txtlanguage2;
    private javax.swing.JTextField txtmediumnow;
    private javax.swing.JTextField txtmediumprevious;
    private javax.swing.JTextField txtpreviousschool;
    private javax.swing.JTextField txtsection;
    // End of variables declaration//GEN-END:variables
}
